version: "2"
services:

  redis:
    image: redis:5-alpine
    command: redis-server --save "" --appendonly no
    volumes:
      - ${PWD}/volumes/redis-data:/data
    restart: unless-stopped
    networks:
      - internal_network
      - external_network
    ports:
      - "6379:6379"

  # manager manages the job queue.
  manager:
    image: quay.io/netzbegruenung/green-spider:latest
    command: >
      python3 cli.py
      --credentials-path /secrets/datastore-writer.json
      --loglevel debug manager
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ${PWD}/secrets:/secrets
    networks:
      - internal_network
      - external_network
    depends_on:
      - redis

  dashboard:
    image: eoranged/rq-dashboard
    environment:
      RQ_DASHBOARD_REDIS_URL: redis://redis:6379/0
    networks:
      - internal_network
      - external_network
    ports:
      - "9181:9181"
    depends_on:
      - redis

networks:
  internal_network:
    internal: true
  external_network:
    internal: false