apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: green-spider-job-psp
  namespace: marian
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - emptyDir
  - secret
